### ISSUE TITLE
Add a "success" test case if no error generated

### ISSUE THREAD

**Issue by huanghugo** [GenoLogics-OpenSource/tslint-junit-formatter#8]
If no tslint errors are generated, please add a "success" test case so that CI tools like Bamboo will not fail on the JUnit task.

**Comment by jkrentz** [comment]
We haven't run into this issue, I have no objections to adding a successful testcase when there are no failures.

**Comment by jkrentz** [comment]
Released 5.1.0

**Comment by huanghugo** [comment]
Great! Tested, it's works. Thanks, @jkrentz
